ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.vakiti.online
REDIS_HOST: redis-dev.vakiti.online
USER_HOST: user-dev.vakiti.online
CATALOGUE_HOST: catalogue-dev.vakiti.online
CART_HOST: cart-dev.vakiti.online
MYSQL_HOST: mysql-dev.vakiti.online
SHIPPING_HOST: shipping-dev.vakiti.online
PAYMENT_HOST: payment-dev.vakiti.online
RABBITMQ_HOST: rabbitmq-dev.vakiti.online
