- name: call common roles
  #ansible.builtin.include_role:
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "RedHat"
  # loop:           # import will fail when it sees loops, You should use 'include_role' instead.
  # - ramesh
  # - suresh
