- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - maven
  - mysql

- name: install dependencie
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: moving the shipping.jar
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app
