- name: message 1
  ansible.builtin.debug:
    msg: "hi from message 1"

- name: set the os fact
  ansible.builtin.set_fact:
    os: "debian" # changing the os variable here from RedHat to debian

# import_roles will skip below tasks where include_roles will print all messages without caring the condtions

- name: message 2
  ansible.builtin.debug:
    msg: "hi from message 2"
- name: message 3
  ansible.builtin.debug:
    msg: "hi from message 3"
